### ISSUE TITLE
New gpg agent messages during upgrade to meta-main.20241122_160415.zos

### ISSUE THREAD

**Issue by gngrossi** [zopencommunity/metaport#69]
Upgraded to meta-main.20241122_160415.zos
Are these messages expected? 

[SYSA] bash-5.2$ zopen upgrade meta
- Querying repo for latest package information.
Processing package: meta
- Replacing meta version 'main.20241120_034335' with 'main.20241122_160415'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3121  100  3121    0     0  14519      0 --:--:-- --:--:-- --:--:-- 14519
- Downloading meta-main.20241122_160415.zos.pax.Z file from remote to zopen package cache...
- Checking available size to install meta.
- Enough space to install meta. Proceeding installation.
- Download complete.
- Processing meta-main.20241122_160415.zos.pax.Z...
After this operation, 23.99 MB of additional disk space will be used.
Do you want to continue? [y/n]
y
**Starting gpg-agent...
gpg-agent[34280252]: can't mmap pool of 32768 bytes: EDC5128I No such device. (errno2=0x07280119) - using malloc
gpg-agent[34280252]: Please note that you don't have secure memory on this system
gpg-agent: a gpg-agent is already running - not starting a new one
gpg-agent started successfully.
gpg: can't mmap pool of 32768 bytes: EDC5128I No such device. (errno2=0x07280119) - using malloc
gpg: Please note that you don't have secure memory on this system
gpg: keybox '/u/@02858/tmp/zopen_gpg_verify_67831844/pubring.kbx' created
gpg: key 6EBA60492F343463: public key "zosopentoolsmain <zosopentoolsmain@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: can't mmap pool of 32768 bytes: EDC5128I No such device. (errno2=0x07280119) - using malloc
gpg: Please note that you don't have secure memory on this system
/u/@02858/tmp/zopen_gpg_verify_67831844/pubring.kbx
---------------------------------------------------
pub   ed25519 2024-10-21 [SC] [expires: 2027-10-21]
      C1A01D8A583E1A6A72BF8AC06EBA60492F343463
uid           [ unknown] zosopentoolsmain <zosopentoolsmain@gmail.com>
sub   cv25519 2024-10-21 [E] [expires: 2027-10-21]**
...

**Comment by IgorTodorovskiIBM** [comment]
At the moment, yes. @HarithaIBM is in the process of updating GPG to eliminate the various warnings. 
@HarithaIBM we may want to only enable these if the -v (verbose) option is specified.

**Comment by gngrossi** [comment]
Sounds good.  I hadn't seen the...
**Starting gpg-agent..  
.gpg-agent: a gpg-agent is already running - not starting a new one
gpg-agent started successfully.**
...messages before while using meta.
closing...thanks
